services:
  - type: web
    name: django-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn creditportal.wsgi --chdir creditportal"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: creditportal.settings
